base_url = "https://nikrev.com"
output_dir = ".public"
build_search_index = false

minify_html = true
default_language = "en"
author = "Nik Revenco"
title = "nik-rev"
description = "A minimalistic Zola theme"
generate_feeds = true

[markdown]
highlight_code = true
highlight_theme = "css"
bottom_footnotes = true
insert_anchor_links = "heading"
smart_punctuation = true
